apiVersion: v1
kind: Service
metadata:
  name: spotify-parser-service
spec:
  type: NodePort  
  selector:
    app: spotify-parser 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080  