name: CD

on:
  workflow_run:
    workflows: [CI]
    branches: 
      - main
    types:
      - completed

jobs:
  push:
    name: Push to Dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build --target prod -t viksun02/devops-project-collab:latest .
          docker push viksun02/devops-project-collab:latest
  
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: push

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Start miniKube
        uses: medyagh/setup-minikube@master

      - name: Get pods
        run: kubectl get pods

      - name: Pull Docker Image
        run: |
          docker pull viksun02/devops-project-collab:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/

      - name: Run Kube-Hunter in Passive Mode
        run: |
          docker run --rm aquasec/kube-hunter --passive

      - name: Check kubernetes status
        run: kubectl get all
      
      - name: Stop the minicube
        run: minikube stop
      
