name: RunApp
on:
  workflow_run:
    workflows: [RunTest]
    branches:
      - '*'
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

    steps:
      - name: Build image
        run: |
          if [ $? -eq 0 ]; then
            docker build --target prod -t parser-app-prod .
          fi

      - name: Run the container
        run: |
          if [ $? -eq 0 ]; then
            docker run parser-app-prod
          fi
