name: RunApp

on:
  workflow_run:
    workflows: [RunTest]
    branches: 
      - '*'
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build image
        run: |
          docker build --target prod -t parser-app-prod .

      - name: Run the container
        run: |
          docker run parser-app-prod
