name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Pylint
        run: python3 -m pip install pylint

      - name: Run Lintian check
        run: pylint src --exit-zero

  static-analysis:
    name: Perform Static Analysis
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bandit
        run: pip install bandit

      - name: Static Code Analysis
        run: bandit -r src/
      
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: static-analysis

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build and Run Tests
        run: |
          docker build --target test -t parser-app-test .
          docker run --rm parser-app-test

  build-and-scan:
    name: Build and scan Docker image
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build Docker Image
        run: docker build -t my-app .

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: my-app

